### ISSUE TITLE
Bind returns false when HttpSetServiceConfiguration returns NO_ERROR

### ISSUE THREAD

**Issue by cklam2** [segor/SslCertBinding.Net#11]
When the specified endpoint was not yet bound to any certificate and you call Bind then false is returned even when the bind was successful. 

```
uint retVal = HttpApi.HttpSetServiceConfiguration(...);
if (HttpApi.ERROR_ALREADY_EXISTS != retVal) {
   HttpApi.ThrowWin32ExceptionIfError(retVal);
}
```

Is this intentional cause the bool return flag is called `bindingUpdated`. In case of new binding it is indeed not 'updated' but created. However from outside the method name it seems to be strange that Bind returns false even when bind was successful?

I propose to change the `if` part as follows:
```
if (HttpApi.NOERROR == retVal) {
   bindingUpdated = true;
} else if (HttpApi.ERROR_ALREADY_EXISTS != retVal) {
   HttpApi.ThrowWin32ExceptionIfError(retVal);
} ...
```

**Comment by segor** [comment]
I agree that Boolean result might be confusing here.  
I think, an enum should be returned instead of bool:
```C#
enum BindingResult {
  Created, // instead of `false`
  Updated // instead of `true`
  //we do not need `Failed` status here in order to an exception  will be raised in case of any error. 
}
```
@cklam2 What do you think would it be more understandable with enum ?

**Comment by cklam2** [comment]
Well, I'm wondering why Bind needs to return whether it was a new bind or a rebind? If you need that info then you can call QueryExact prior to Bind. 
Bind throws an exception when bind fails, it can also be `void Bind(...)` instead. But if you do prefer a return value then the enum is definitely better than a boolean.

**Comment by danielmue** [comment]
Hi,
I would prefer a simple void method. In case the binding request fails, it should throw a good exception. Such as 'AccessDeniedException' or 'InvalidCertificateThumbprintException' .. 
As @cklam2 said, the information _has been created_ or _updated_ does not offer much value.
:-)

**Comment by sergeyg-earnin** [comment]
Agree, `void` would be better here.
