### ISSUE TITLE
I created a .Net Standard fork

### ISSUE THREAD

**Issue by pablocar80** [segor/SslCertBinding.Net#14]
Hello! I created a fork of this project that targets .NET Standard 2.0, so I could use it not only in Windows but also in Linux and iOS:

https://github.com/pablocar80/SslCertBinding.Net

Would you like to merge it to your project?

**Comment by sergeyg-earnin** [comment]
This library relies on WIN32 API, so I don't think it will work on non-Windows OS

**Comment by pablocar80** [comment]
Oh. It let me compile and I thought I was good. I see the API calls now. Nevermind then. You could still take the changes if you want to be able to compile on Mono or NET Core and then run on Windows.

**Comment by pablocar80** [comment]
Cancelling request -- there are win32 dependencies
