### ISSUE TITLE
.NET Core / .NET Standard support for Windows-only environments

### ISSUE THREAD

**Issue by andy1547** [segor/SslCertBinding.Net#16]
It's possible to use the HTTP Server API with ASP.NET Core projects, see https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/?view=aspnetcore-5.0&tabs=windows

Are there any plans to make this project available in .NET Core, perhaps by targeting .NET Standard 2.0? Does this project still need to support .NET Framework 2.0 (if so multi-targeting could be used)?

**Comment by segor** [comment]
This library was designed for .Net Framework and I do not have any plans to port it to .net core.
But I appreciate any contribution to this project. Also feel free to build a new project on top of this one.

**Comment by segor** [comment]
Similar to #14

**Comment by andy1547** [comment]
Depending on the hosting model for ASP.NET Core, HTTP.sys may still be used (either directly or indirectly by IIS), so there may be value in porting this package over. To my knowledge Kestrel server doesn't use HTTP.sys, which is the recommend option for self-hosted apps. For the 4 possible hosting options, see https://learn.microsoft.com/en-us/aspnet/core/fundamentals/servers/?view=aspnetcore-7.0&tabs=windows#hosting-models

There are .NET Standard/Core packages that are intended to be used solely on Windows, the biggest example being Microsoft.Windows.Compatibility. Moreover, it may be that including the compatibility package is enough to get this library working out the box with .NET Standard 2.0.

For some background, we currently use this project at application startup, binding a SSL certificate to a specific port before booting a self-hosted ASP.NET OWIN app that listens for HTTPs traffic. By default the OWIN implementation (Katana) uses HttpListener as its server (which uses HTTP.sys), when we migrate to ASP.NET Core we may still need this library for dynamically binding a SSL certificate (depending on the hosting model we choose).

**Comment by Mertsch** [comment]
In addition to that there is explicitly the concept of
`if (OperatingSystem.IsWindows()) { ... }`
and
`[SupportedOSPlatform("windows")]`
which are perfect for this library.
As the user mentioned before `HHTP.sys` is a real thing and this package make for a perfect companion. Also note that ignoring the .NET Framework warning makes for a working package under .NET 6 and 7 and most likely 8.

So making this a .NET 6 and soon .NET 8 package would be a perfect fit and a great upgrade.

**Comment by segor** [comment]
@andy1547, @Mertsch . I have added .NET Core support in the `dev` branch. Can please check the version [2.0.0-beta](https://www.nuget.org/packages/SslCertBinding.Net/2.0.0-beta) and let me know if it does work for you?

**Comment by andy1547** [comment]
We've integrated with the v2.0.0 package and can confirm it works as intended, thanks!
