### ISSUE TITLE
Неправильное значение в DefaultCertCheckMode (CertificateBindingConfiguration.cs:34)

### ISSUE THREAD

**Issue by rats-gr** [segor/SslCertBinding.Net#5]
File CertificateBindingConfiguration.cs, line 43
(options.DoNotVerifyCertificateRevocation ? HttpApi.CertCheckModes.EnableRevocationFreshnessTime : 0)
нужно заменить на
(options.EnableRevocationFreshnessTime ? HttpApi.CertCheckModes.EnableRevocationFreshnessTime : 0)

**Comment by segor** [comment]
Thanks for report.

**Comment by segor** [comment]
Fixed, published v.1.0.2
