### ISSUE TITLE
Trying to use this and failing.

### ISSUE THREAD

**Issue by jerblackmer** [segor/SslCertBinding.Net#9]
I have converted this code to initiate it into VB.net.  I have compiled your resources into a DDL from the C# code.
  
If my understanding is correct this should generate a certificate as well or does it need to be added to the CERT STORE prior?

Can I use any port with this?
Do I need to specify an ip other then 0.0.0.0?
Do I need to change the thumbprint and appid?

config.Bind(certificateBinding)  is returning true... does this mean it was successful?

            dim porttouse as long = 2003         
           
            Dim config As ICertificateBindingConfiguration = New CertificateBindingConfiguration()
            Dim ipPort As IPEndPoint = New IPEndPoint(IPAddress.Parse("0.0.0.0"), porttouse)
            Dim certificateThumbprint As String = "372680E4AEC4A57CAE698307347C65D3CE38AF60"
            Dim appId As Guid = Guid.Parse("214124cd-d05b-4309-9af9-9caa44b2b74a")

            'add a new binding record
            config.Bind(New CertificateBinding(certificateThumbprint, StoreName.My, ipPort, appId))

            'get a binding record
            Dim certificateBinding = config.Query(ipPort)(0)

            'set an option and update the binding record
            certificateBinding.Options.DoNotVerifyCertificateRevocation = True
            If config.Bind(certificateBinding) Then

            End If

**Comment by segor** [comment]
> If my understanding is correct this should generate a certificate as well or does it need to be added to the CERT STORE prior?

This library just manages binding an between existing certificate  and network endpoint. So you have to add your own certificate to certificate store before binding.   You can do it manually or by using standard .Net classes. See an example in unit tests , method `TestInitialize()`, file [UnitTests.cs](/segor/SslCertBinding.Net/blob/master/src/SslCertBinding.Net.Tests/UnitTests.cs). 

> Can I use any port with this?

You have to specify ip and port that your web server uses for listening incoming http-connections.

> Do I need to specify an ip other then 0.0.0.0?

 In most cases you may use ip 0.0.0.0

>  Do I need to change the thumbprint and appid?

Yes, you have to specify a thumbprint of a certificate in store and generate a new GUID that will identify your application.

> config.Bind(certificateBinding) is returning true

It means that the record has been replaced with new one. ` config.Bind(certificateBinding)` returns `false` if record has been added.

Note  your app has to have admin right to make changes.
